env:
  node: true
  jest: true
parserOptions:
  ecmaVersion: 2020
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
plugins:
  - jest
rules:
  no-console: 0
  arrow-body-style: 2
  no-multiple-empty-lines: 1
  consistent-return: 1
  array-callback-return: 2
  max-len: [
      2,
      {
        "code": 100,
        "ignoreComments": true
      }
  ]
