env:
  node: true
  jest: true
parser: '@typescript-eslint/parser'
extends:
  - 'airbnb-base'
  - 'airbnb-typescript/base'
  - 'plugin:jest/recommended'
plugins:
  - jest
rules:
  no-console: 0
  arrow-body-style: 2
  no-multiple-empty-lines: 1
  consistent-return: 1
  array-callback-return: 2
  max-len: [
      2,
      {
        "code": 100,
        "ignoreComments": true
      }
  ]

overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    extends:
      - 'plugin:@typescript-eslint/recommended'
      - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
    parserOptions:
      project:
        - ./tsconfig.json
